added push notifications for todays events and navigation to relevant…
tarunaidoo/Infrastructure_Management pull request #33
Opened 2024-09-12 16:36 UTC by skassen2

… home pages

2024-09-12 17:38 UTC, tarunaidoo approved these changes

2024-09-12 19:54 UTC, NtandoRaji requested changes

2024-09-12 19:54 UTC, NtandoRaji commented on src/components/NotificationPopup/NotificationPopup.jsx
We have a component with the "Popup" in the "Popup" component directory. I'd suggest just naming the NotificationPopup component from Popup to NotificationPopup

2024-09-13 06:25 UTC, skassen2 commented on src/components/NotificationPopup/NotificationPopup.jsx
I made the change

2024-09-13 07:00 UTC, NtandoRaji approved these changes

2024-09-13 07:04 UTC, merged