Complete Component and unit testing for Event Details page
tarunaidoo/Infrastructure_Management pull request #42
Opened 2024-09-16 17:34 UTC by JaedonM23

Added component testing for Event Details Header and Card Component
Added additional unit test in home page services for delete booking function

2024-09-16 18:24 UTC, Tania908 requested changes
I have changed the tests so that everything is passing now. Rather wait for my stuff to be merged on to main first as my old tests are creating fails for the run test part.

2024-09-17 10:24 UTC, Tania908 commented
Pull from main now and create a new pull request and it should work now

2024-09-17 10:55 UTC, Tania908 approved these changes

2024-09-17 10:56 UTC, skassen2 approved these changes

2024-09-17 10:59 UTC, merged